mv dataTT-B_svFit_MELA.root data_B.root
mv dataTT-C_svFit_MELA.root data_C.root
mv dataTT-D_svFit_MELA.root data_D.root
mv dataTT-E_svFit_MELA.root data_E.root
mv dataTT-F_svFit_MELA.root data_F.root
mv dataTT-G_svFit_MELA.root data_G.root
mv dataTT-H_svFit_MELA.root data_H.root
mv DYJets1_svFit_MELA.root DY1.root
mv DYJets2_svFit_MELA.root DY2.root
mv DYJets3_svFit_MELA.root DY3.root
mv DYJets4_svFit_MELA.root DY4.root
mv DYJets_svFit_MELA.root  DY.root
mv EWKWMinus_svFit_MELA.root EWKWMinus.root
mv EWKWPlus_svFit_MELA.root EWKWPlus.root
mv EWKZ2l_svFit_MELA.root  EWKZ2l.root
mv EWKZ2nu_svFit_MELA.root EWKZ2nu.root
mv ggHtoTauTau125_svFit_MELA.root ggH125.root
mv ggH_WW125_svFit_MELA.root ggH_WW125.root
mv Tbar-tchan_svFit_MELA.root Tbar-tchan.root
mv Tbar-tW_svFit_MELA.root Tbar-tW.root
mv T-tchan_svFit_MELA.root T-tchan.root
mv TT_svFit_MELA.root  TT.root
mv T-tW_svFit_MELA.root T-tW.root
mv VBFHtoTauTau125_svFit_MELA.root VBF125.root
mv VBF_WW125_svFit_MELA.root VBF_WW125.root
mv VV_svFit_MELA.root VV.root
mv WGLNu_svFit_MELA.root WGLNu.root
mv WGstarEE_svFit_MELA.root WGstarEE.root
mv WGstarMuMu_svFit_MELA.root WGstarMuMu.root
mv WJets1_svFit_MELA.root W1.root
mv WJets2_svFit_MELA.root W2.root
mv WJets3_svFit_MELA.root W3.root
mv WJets4_svFit_MELA.root W4.root
mv WJets_svFit_MELA.root W.root
mv WMinusHTauTau125_svFit_MELA.root WminusH125.root
mv WPlusHTauTau125_svFit_MELA.root WplusH125.root
mv WWW_svFit_MELA.root WWW.root
mv WZ1l1nu2q_svFit_MELA.root WZ1l1nu2q.root
mv WZ1l3nu_svFit_MELA.root WZ1l3nu.root
mv WZ2l2q_svFit_MELA.root WZ2l2q.root
mv WZ3l1nu_svFit_MELA.root WZ3l1nu.root
mv ZHTauTau125_svFit_MELA.root ZH125.root

